include catppuccin-mocha.conf

kitty_mod ctrl+shift

confirm_os_window_close -1
map kitty_mod+n new_os_window_with_cwd
map kitty_mod+t new_tab_with_cwd

map kitty_mod+h previous_tab
map kitty_mod+l next_tab

enabled_layouts splits:split_axis=horizontal, stack
map kitty_mod+' launch --cwd=current --location=hsplit

map kitty_mod+\ toggle_layout stack

# map ctrl+w>j kitten pass_keys.py bottom 'ctrl+w>j'
# map ctrl+w>k kitten pass_keys.py top    'ctrl+w>k'
# map ctrl+w>h kitten pass_keys.py left   'ctrl+w>h'
# map ctrl+w>l kitten pass_keys.py right  'ctrl+w>l'
map ctrl+j kitten pass_keys.py bottom ctrl+j
map ctrl+k kitten pass_keys.py top    ctrl+k
map ctrl+h kitten pass_keys.py left   ctrl+h
map ctrl+l kitten pass_keys.py right  ctrl+l

shell_integration enabled

allow_remote_control yes
listen_on unix:@mykitty

