#!/usr/bin/env bash

name="$1"
cwd=$(pwd)

mkdir "$(pwd)/$name"
cp ~/.config/hypr/scripts/templates/cp-template.cpp "$(pwd)/$name/sol.cpp"
cp ~/.config/hypr/scripts/templates/debugging.h "$(pwd)/$name/debugging.h"
cd "$name"
