#!/usr/bin/env bash

name="$1"

if [[ "$name" != "system" && "$name" != "tray" && "$name" != "pomo" ]]; then
    exit 1
fi

lock_file="$HOME/.cache/eww-$name.lock"
if [[ ! -f "$lock_file" ]]; then
    touch "$lock_file"
    eww open $name --screen $(hyprctl monitors -j | jq -r '.[] | select(.focused == true) | .name')
else
    eww close "$name"
    rm "$lock_file"
fi
